=== a82298/DWeb2019/TP2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT PROJECT (INFO,WORKTEAM,ABSTRACT,DELIVERABLES,FOOTER)>
<!ELEMENT INFO (KEYNAME,TITLE,SUBTITLE,BEGINDATE,ENDATE,SUPERVISOR) >

<!ELEMENT KEYNAME (#PCDATA) >
<!ELEMENT TITLE (#PCDATA) >
<!ELEMENT SUBTITLE (#PCDATA) >
<!ELEMENT BEGINDATE (#PCDATA) >
<!ELEMENT ENDATE (#PCDATA) >
<!ELEMENT SUPERVISOR (#PCDATA)>
<!ATTLIST SUPERVISOR 
                    REF CDATA #IMPLIED>
<!ELEMENT WORKTEAM (MEMBER)+ >
<!ELEMENT MEMBER (#PCDATA) >
<!ATTLIST MEMBER 
                REF CDATA #IMPLIED>
<!ELEMENT ABSTRACT (#PCDATA)>
<!ELEMENT DELIVERABLES (DELIVERABLE)*>
<!ELEMENT DELIVERABLE (#PCDATA) >
<!ATTLIST DELIVERABLE
                   REF CDATA #REQUIRED>
<!ELEMENT FOOTER (#PCDATA) >

=== a82298/DWeb2019/TP2/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PROJECT SYSTEM "PR.dtd">
<PROJECT>
    <INFO>
        <KEYNAME></KEYNAME>
        <TITLE></TITLE>
        <SUBTITLE></SUBTITLE>
        <BEGINDATE></BEGINDATE>
        <ENDATE></ENDATE>
        <SUPERVISOR></SUPERVISOR>
    </INFO>
    <WORKTEAM>
        <MEMBER></MEMBER>
    </WORKTEAM>
    <ABSTRACT></ABSTRACT>
    <DELIVERABLES>
        <DELIVERABLE REF=""></DELIVERABLE>
    </DELIVERABLES>
    <FOOTER></FOOTER>
</PROJECT>
